In [95]:
import pandas
from time import time
kdd_data_train = pandas.read_csv("/Users/wandawang/Desktop/NSL_KDD-master/new.KDD.train.csv")
#kdd_data_train.describe()

In [85]:
import pandas
from time import time
kdd_data_train1 = pandas.read_csv("/Users/wandawang/Desktop/NSL_KDD-master/kdd_data_train.csv").astype(float)
kdd_data_train1.describe()

,duration,src_bytes,dst_bytes,land,wrong_fragment,urgent,hot,num_failed_logins,logged_in,num_compromised,...,dst_host_srv_count,dst_host_same_srv_rate,dst_host_diff_srv_rate,dst_host_same_src_port_rate,dst_host_srv_diff_host_rate,dst_host_serror_rate,dst_host_srv_serror_rate,dst_host_rerror_rate,dst_host_srv_rerror_rate,outcome.response
count,125973.00000,1.259730e+05,1.259730e+05,125973.000000,125973.000000,125973.000000,125973.000000,125973.000000,125973.000000,125973.000000,...,125973.000000,125973.000000,125973.000000,125973.000000,125973.000000,125973.000000,125973.000000,125973.000000,125973.000000,125973.000000
mean,287.14465,4.556674e+04,1.977911e+04,0.000198,0.022687,0.000111,0.204409,0.001222,0.395736,0.279250,...,115.653005,0.521242,0.082951,0.148379,0.032542,0.284452,0.278485,0.118832,0.120240,0.465417
std,2604.51531,5.870331e+06,4.021269e+06,0.014086,0.253530,0.014366,2.149968,0.045239,0.489010,23.942042,...,110.702741,0.448949,0.188922,0.308997,0.112564,0.444784,0.445669,0.306557,0.319459,0.498805
min,0.00000,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.00000,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,10.000000,0.050000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,0.00000,4.400000e+01,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,63.000000,0.510000,0.020000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,0.00000,2.760000e+02,5.160000e+02,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,...,255.000000,1.000000,0.070000,0.060000,0.020000,1.000000,1.000000,0.000000,0.000000,1.000000
max,42908.00000,1.379964e+09,1.309937e+09,1.000000,3.000000,3.000000,77.000000,5.000000,1.000000,7479.000000,...,255.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [112]:
df = kdd_data_train1.astype(float)

In [109]:
import pandas as pd
from sklearn.preprocessing import MinMaxScaler

In [117]:
scaler = MinMaxScaler()
kdd_data_train1 = pd.DataFrame(scaler.fit_transform(df), columns=df.columns)
kdd_data_train1.describe()

,duration,src_bytes,dst_bytes,land,wrong_fragment,urgent,hot,num_failed_logins,logged_in,num_compromised,...,dst_host_srv_count,dst_host_same_srv_rate,dst_host_diff_srv_rate,dst_host_same_src_port_rate,dst_host_srv_diff_host_rate,dst_host_serror_rate,dst_host_srv_serror_rate,dst_host_rerror_rate,dst_host_srv_rerror_rate,outcome.response
count,125973.000000,1.259730e+05,1.259730e+05,125973.000000,125973.000000,125973.000000,125973.000000,125973.000000,125973.000000,125973.000000,...,125973.000000,125973.000000,125973.000000,125973.000000,125973.000000,125973.000000,125973.000000,125973.000000,125973.000000,125973.000000
mean,0.006692,3.302024e-05,1.509928e-05,0.000198,0.007562,0.000037,0.002655,0.000244,0.395736,0.000037,...,0.453541,0.521242,0.082951,0.148379,0.032542,0.284452,0.278485,0.118832,0.120240,0.465417
std,0.060700,4.253974e-03,3.069818e-03,0.014086,0.084510,0.004789,0.027922,0.009048,0.489010,0.003201,...,0.434128,0.448949,0.188922,0.308997,0.112564,0.444784,0.445669,0.306557,0.319459,0.498805
min,0.000000,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000000,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.039216,0.050000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,0.000000,3.188489e-08,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.247059,0.510000,0.020000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,0.000000,2.000052e-07,3.939120e-07,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,...,1.000000,1.000000,0.070000,0.060000,0.020000,1.000000,1.000000,0.000000,0.000000,1.000000
max,1.000000,1.000000e+00,1.000000e+00,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [115]:
kdd_data_train['outcome.response'].value_counts()

0    67343
1    58630
Name: outcome.response, dtype: int64

In [118]:
from sklearn.cluster import KMeans
k = 30
km = KMeans(n_clusters = k)


t0 = time()
km.fit(kdd_data_train1)
tt = time()-t0
print "Clustered in {} seconds".format(round(tt,3))

Clustered in 24.211 seconds

In [119]:
pandas.Series(km.labels_).value_counts()

0     17561
20    16170
1     14695
19    12956
4      8293
2      6902
24     6091
3      4167
9      3871
10     3299
6      2858
22     2637
14     2563
13     2104
5      2033
28     1777
12     1697
11     1665
16     1657
8      1657
29     1383
7      1377
21     1307
17     1297
25     1255
18     1159
27     1100
15     1033
26      968
23      441
dtype: int64

In [127]:
labels = kdd_data_train1['outcome.response']
label_names = map(
    lambda x: pandas.Series([labels[i] for i in range(len(km.labels_)) if km.labels_[i]==x]), 
    range(k))

In [128]:
for i in range(k):
    print "Cluster {} labels:".format(i)
    print label_names[i].value_counts()
    print

Cluster 0 labels:
1.0    17561
dtype: int64

Cluster 1 labels:
0.0    14337
1.0      358
dtype: int64

Cluster 2 labels:
1.0    6895
0.0       7
dtype: int64

Cluster 3 labels:
1.0    4164
0.0       3
dtype: int64

Cluster 4 labels:
0.0    8293
dtype: int64

Cluster 5 labels:
0.0    2033
dtype: int64

Cluster 6 labels:
0.0    2790
1.0      68
dtype: int64

Cluster 7 labels:
0.0    1375
1.0       2
dtype: int64

Cluster 8 labels:
1.0    1657
dtype: int64

Cluster 9 labels:
0.0    3871
dtype: int64

Cluster 10 labels:
0.0    3260
1.0      39
dtype: int64

Cluster 11 labels:
1.0    1665
dtype: int64

Cluster 12 labels:
1.0    1448
0.0     249
dtype: int64

Cluster 13 labels:
1.0    2089
0.0      15
dtype: int64

Cluster 14 labels:
0.0    2538
1.0      25
dtype: int64

Cluster 15 labels:
1.0    969
0.0     64
dtype: int64

Cluster 16 labels:
0.0    1630
1.0      27
dtype: int64

Cluster 17 labels:
0.0    1297
dtype: int64

Cluster 18 labels:
0.0    848
1.0    311
dtype: int64

Cluster 19 labels:
0.0    12956
dtype: int64

Cluster 20 labels:
1.0    16170
dtype: int64

Cluster 21 labels:
1.0    1307
dtype: int64

Cluster 22 labels:
0.0    2632
1.0       5
dtype: int64

Cluster 23 labels:
1.0    435
0.0      6
dtype: int64

Cluster 24 labels:
0.0    6091
dtype: int64

Cluster 25 labels:
0.0    1255
dtype: int64

Cluster 26 labels:
1.0    968
dtype: int64

Cluster 27 labels:
1.0    1084
0.0      16
dtype: int64

Cluster 28 labels:
0.0    1777
dtype: int64

Cluster 29 labels:
1.0    1383
dtype: int64

In [122]:
km.labels_

array([22, 28, 20, ..., 10, 20, 10], dtype=int32)

In [123]:
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt
print kdd_data_train1[:0]

Empty DataFrame
Columns: [duration, src_bytes, dst_bytes, land, wrong_fragment, urgent, hot, num_failed_logins, logged_in, num_compromised, root_shell, su_attempted, num_root, num_file_creations, num_shells, num_access_files, num_outbound_cmds, is_host_login, is_guest_login, count, srv_count, serror_rate, srv_serror_rate, rerror_rate, srv_rerror_rate, same_srv_rate, diff_srv_rate, srv_diff_host_rate, dst_host_count, dst_host_srv_count, dst_host_same_srv_rate, dst_host_diff_srv_rate, dst_host_same_src_port_rate, dst_host_srv_diff_host_rate, dst_host_serror_rate, dst_host_srv_serror_rate, dst_host_rerror_rate, dst_host_srv_rerror_rate, outcome.response]
Index: []

[0 rows x 39 columns]

In [124]:
km.cluster_centers_

array([[  1.97758476e-15,   7.17606313e-18,  -2.99680257e-18, ...,
          3.36541199e-04,  -3.32789352e-14,   1.00000000e+00],
       [  2.36244552e-05,   1.13860093e-06,   3.09362237e-06, ...,
          2.71929228e-03,   2.76556652e-03,   2.43620279e-02],
       [  6.41564564e-08,   1.12488718e-09,   9.73323432e-11, ...,
          9.99465372e-01,   9.99642133e-01,   9.98985801e-01],
       ...,
       [  1.23729841e-03,   5.95733639e-09,   5.11301324e-08, ...,
          5.46427273e-01,   9.91390909e-01,   9.85454545e-01],
       [  9.32641268e-02,   1.05930773e-07,   6.62340972e-08, ...,
          1.57568936e-04,   3.19189120e-16,   9.82547377e-15],
       [  4.46899421e-03,   1.55029928e-04,   4.63402637e-05, ...,
          3.93058568e-02,   3.24367317e-02,   1.00000000e+00]])